site_name: Interdimensional

repo_url: https://github.com/QuiltServerTools/Interdimensional
repo_name: QuiltServerTools/Interdimensional

nav:
  - index.md
  - Commands:
      - commands/root.md
      - commands/create.md
      - commands/delete.md
      - commands/portal.md
  - GUIs:
      - guis/create.md
theme:
  name: material
  features:
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: cyan
    scheme: slate

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
extra:
  version:
    provider: mike